version: '2'
services:
  ansible:
    build: ./ansible
    volumes:
     - ./ansible:/opt
  api1:
    build: ./api
  api2:
    build: ./api
  batch1:
    build: ./batch
  batch2:
    build: ./batch
networks:
  default:
