---
ansistrano_deploy_to: /opt/app
ansistrano_shared_paths:
  - cache
  - logs
  - tmp
ansistrano_allow_anonymous_stats: no
ansistrano_keep_releases: 5
ansistrano_get_url:  https://github.com/kashiwaguma-hiro/ansistrano_sandbox/archive/master.zip
