---
ansistrano_deploy_to: /opt/app
ansistrano_shared_paths:
  - cache
  - logs
  - tmp
ansistrano_allow_anonymous_stats: no
ansistrano_keep_releases: 5
ansistrano_deploy_via: git
ansistrano_git_repo: git@github.com:kashiwaguma-hiro/haskell-hello.git
ansistrano_git_branch: master
#ansistrano_after_update_code_tasks_file: "{{ playbook_dir }}/roles/hooks/task/after_update_code.yml"
#ansistrano_after_update_code_tasks_file: "{{ playbook_dir }}/roles/hooks/tasks/before_symlink_shared.yml"
#ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/roles/hooks/task/after_symlink.yml"
