---
# Artifact setting.
download_dir: /tmp
artifact_download_url:  "https://github.com/curl/curl/archive/{{ module_name }}?v={{ version | default('latest') }}"

# Ansistrano setting.
ansistrano_deploy_via: copy
ansistrano_deploy_from: "{{ download_dir }}/{{ major_version }}/{{ module_name }}"
ansistrano_keep_releases: 3
ansistrano_allow_anonymous_stats: no
ansistrano_before_update_code_tasks_file: '{{ playbook_dir }}/roles/artifact/tasks/download.yml'