---
# Download setting.
artifact_url:  "{{ artifact_base_url }}/{{ api_module_name }}?v={{ version | default('latest') }}"
api_module_name : master.zip

# Mainte setting.
mainte_file_src: /tmp/src/mainte.html
mainte_file_dest: /tmp/dest/mainte.html

# Ansistrano setting.
ansistrano_deploy_to: /opt/api/bin/
ansistrano_before_setup_tasks_file: "{{ playbook_dir }}/roles/api/tasks/release_init.yml"
ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/roles/api/tasks/stop.yml"
ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/roles/api/tasks/start.yml"
ansistrano_after_cleanup_tasks_file: "{{ playbook_dir }}/roles/api/tasks/release_term.yml"