---
# Download setting.
artifact_url:  "{{ artifact_base_url }}/{{ subscriber_module_name }}?v={{ version | default('latest') }}"
subscriber_module_name : master.zip

# Ansistrano setting.
ansistrano_deploy_to: /opt/batch/bin/
ansistrano_before_setup_tasks_file: "{{ playbook_dir }}/roles/zabbix/tasks/mainte_off.yml"
# ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/roles/subscriber/tasks/stop.yml"
# ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/roles/subscriber/tasks/start.yml"
ansistrano_before_setup_tasks_file: "{{ playbook_dir }}/roles/zabbix/tasks/mainte_on.yml"