---
# Ansistrano setting.
ansistrano_deploy_to: "/opt/batch/bin/{{ major_version }}/{{ module_name }}"
ansistrano_before_setup_tasks_file: "{{ playbook_dir }}/roles/zabbix/tasks/mainte_mode_off.yml"
ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/roles/subscriber/tasks/stop.yml"
ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/roles/subscriber/tasks/start.yml"
ansistrano_after_cleanup_tasks_file: "{{ playbook_dir }}/roles/zabbix/tasks/mainte_mode_on.yml"