---
- name: ANSISTRANO | download | Download artifact to local
  get_url:
    url: "{{ artifact_download_url }}"
    dest: "{{ download_dir }}/{{ module_name }}"
    force: yes 
  delegate_to: 127.0.0.1
