---
- name: ACCOUNTING | load balancer detouch | Put health_check_ng file
  command: cp -p {{ health_check_ng_file_src }} {{ health_check_ng_file_dest }}
  args:
    creates: health_check_ng_file_dest
  tags:
    - load_balancer_detouch